SETTINGS:
    SLEEP_BETWEEN_TASKS: [1, 6]
    SLEEP_BETWEEN_WALLETS: [1, 2]
    SIMULTANEOUS_ACCOUNTS_IN_WORK: 6

SOLVERS:
    CAPSOLVER_API_KEY: ""

OPENAI_API_KEY: ""

SELF_SENDER:
    SEND_FROM_PK: ""
    SEND_AMOUNT: [0.01, 0.03]

MEMEBRIDGE:
    SOURCE_CHAIN: "Base" # "Base" / "Optimism" / "Arbitrum"
    BUY_AMOUNT: [0.0002, 0.0003]
    MINIMUM_SAHARA: 1 # Not buy when SAHARA > MINIMUM_SAHARA